package HotelBookingSystem.app;
        
public class LogInWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogInWindow.class.getName());

    /**
     * Creates new form LogInWindow
     */
    public LogInWindow() {
        initComponents();
        
        setSize(800, 600);
        setLocationRelativeTo(null);
        
        headerPanel.setPreferredSize(new java.awt.Dimension(0, 100));
        
        windowPanel.removeAll();
        
        windowPanel.setLayout(new java.awt.GridBagLayout());

        windowPanel.add(headerPanel, new java.awt.GridBagConstraints() {{
        gridx = 0;
        gridy = 0;
        anchor = java.awt.GridBagConstraints.NORTH;
        fill = java.awt.GridBagConstraints.HORIZONTAL;
        weightx = 1.0;
    }});
        
        headerPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        
        headerPanel.add(WelcomeLabel, gbc);

        windowPanel.add(logInPanel, new java.awt.GridBagConstraints() {{
        gridx = 0;
        gridy = 1;
        anchor = java.awt.GridBagConstraints.CENTER;
        weightx = 1.0;
        weighty = 1.0;
    }});
         
         windowPanel.revalidate();
         windowPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        WelcomeLabel = new java.awt.Label();
        logInPanel = new javax.swing.JPanel();
        passwordTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        customerLogInButton = new javax.swing.JButton();
        clerkLogInButton = new javax.swing.JButton();
        closeAppButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowPanel.setBackground(new java.awt.Color(255, 255, 255));
        windowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(102, 204, 255));

        WelcomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WelcomeLabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        WelcomeLabel.setName("WelcomeLabel"); // NOI18N
        WelcomeLabel.setText("Welcome to the Hotel Booking System!"); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        windowPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 405, 70));

        logInPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        passwordTextField.setText("password...");
        passwordTextField.addActionListener(this::passwordTextFieldActionPerformed);

        emailTextField.setText("email...");

        customerLogInButton.setBackground(new java.awt.Color(0, 204, 255));
        customerLogInButton.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        customerLogInButton.setForeground(new java.awt.Color(51, 51, 51));
        customerLogInButton.setText("Log In as Customer");
        customerLogInButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customerLogInButton.setBorderPainted(false);
        customerLogInButton.addActionListener(this::customerLogInButtonActionPerformed);

        clerkLogInButton.setBackground(new java.awt.Color(0, 255, 51));
        clerkLogInButton.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        clerkLogInButton.setText("Log In as Clerk");
        clerkLogInButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clerkLogInButton.setBorderPainted(false);

        closeAppButton.setBackground(new java.awt.Color(255, 51, 51));
        closeAppButton.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        closeAppButton.setText("Close Program");
        closeAppButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeAppButton.setBorderPainted(false);

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeAppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clerkLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(customerLogInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clerkLogInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(closeAppButton)
                .addGap(16, 16, 16))
        );

        windowPanel.add(logInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 270, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void customerLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerLogInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerLogInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogInWindow().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label WelcomeLabel;
    private javax.swing.JButton clerkLogInButton;
    private javax.swing.JButton closeAppButton;
    private javax.swing.JButton customerLogInButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables
}
