package HotelBookingSystem.app;

import HotelBookingSystem.db.DBManager;
import HotelBookingSystem.repository.*;
import HotelBookingSystem.service.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class MainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    public StartupPanel startUpPanel;
    public LoginPanel logInPanel;
    public RegisterPanel registerPanel;
    public CustomerPanel customerPanel;
    public ClerkPanel clerkPanel;
    public GUICommands gui;
    public AuthService authService;
    public DBManager db;
    public BookingManager manager;

    public MainWindow() {

        initComponents();
        db = DBManager.startup();
        IRoomRepository roomRepo = new JdbcRoomRepository(db);
        IUserRepository userRepo = new JdbcUserRepository(db);
        IBookingRepository bookingRepo = new JdbcBookingRepository(roomRepo, db);
        IPaymentProcessor payment = new PaymentProcessor(db);
        manager = new BookingManager(roomRepo, bookingRepo, payment);
        authService = new AuthService(userRepo, manager);

        startUpPanel = new StartupPanel();
        logInPanel = new LoginPanel();
        registerPanel = new RegisterPanel();
        customerPanel = new CustomerPanel();
        clerkPanel = new ClerkPanel();

        gui = new GUICommands(this, authService, manager, roomRepo, bookingRepo, db);

        startUpPanel.setGUI(gui);
        logInPanel.setGUI(gui);
        registerPanel.setGUI(gui);
        customerPanel.setGUI(gui);
        clerkPanel.setGUI(gui);

        MainPanel.setLayout(new CardLayout());
        MainPanel.add(startUpPanel, "startupPanel");
        MainPanel.add(logInPanel, "loginPanel");
        MainPanel.add(registerPanel, "registerPanel");
        MainPanel.add(customerPanel, "customerPanel");
        MainPanel.add(clerkPanel, "clerkPanel");

        startUpPanel.setBounds(0, 0, 900, 700);
        logInPanel.setBounds(0, 0, 900, 700);
        registerPanel.setBounds(0, 0, 900, 700);
        customerPanel.setBounds(0, 0, 900, 700);
        clerkPanel.setBounds(0, 0, 900, 700);

        startUpPanel.setVisible(true);
        logInPanel.setVisible(false);
        registerPanel.setVisible(false);
        customerPanel.setVisible(false);
        clerkPanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Booking System\n");
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(900, 700));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public RegisterPanel getRegisterPanel() {
        return registerPanel;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel MainPanel;
    // End of variables declaration//GEN-END:variables
}
